# Generated by Django 5.2.6 on 2025-10-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('basket', 'Basket'), ('football', 'Football'), ('badminton', 'Badminton'), ('volley', 'Volley'), ('baseball', 'Baseball'), ('padel', 'Padel'), ('tennis', 'Tennis'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('fitness', 'Fitness'), ('yoga', 'Yoga'), ('hiking', 'Hiking'), ('climbing', 'Climbing'), ('skiing', 'Skiing'), ('snowboarding', 'Snowboarding'), ('golf', 'Golf'), ('fishing', 'Fishing'), ('camping', 'Camping'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
